import React, { useState, useMemo } from 'react';
import type { Prescription } from '../lib/types';
import {
  FileText, Activity, ShieldCheck, Apple, CalendarClock, BadgeIndianRupee,
  CheckCircle2, AlertTriangle, AlertCircle, MessageSquare, ChevronRight,
  TrendingUp, Pill
} from 'lucide-react';
import RxGuardChat from './RxGuardChat';
import { mapPrescriptionToRxGuard } from '../utils/rxguardMapper';

interface Props {
  prescription: Prescription;
  clinicalData: any;
  patientProfile: any;
  onViewTimeline: () => void;
}

type TabType = 'report' | 'overview' | 'interactions' | 'dosage' | 'insurance' | 'food' | 'validity';

const tabs = [
  { id: 'report',       label: 'Clinical Report',    icon: TrendingUp },
  { id: 'overview',     label: 'Medications',        icon: Pill },
  { id: 'interactions', label: 'Interactions',       icon: Activity },
  { id: 'dosage',       label: 'Dosage',             icon: ShieldCheck },
  { id: 'insurance',    label: 'Coverage',           icon: BadgeIndianRupee },
  { id: 'food',         label: 'Dietary',            icon: Apple },
  { id: 'validity',     label: 'Validity',           icon: CheckCircle2 },
] as const;

function Badge({ level }: { level: string }) {
  const cls =
    level === 'HIGH'    ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :
    level === 'MEDIUM'  ? 'bg-amber-50 text-amber-700 border-amber-200' :
    level === 'CRITICAL'|| level === 'MAJOR' ? 'bg-red-50 text-red-700 border-red-200' :
                          'bg-gray-100 text-gray-600 border-gray-200';
  return <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded border ${cls}`}>{level}</span>;
}

export function ResultsScreen({ prescription, clinicalData, patientProfile, onViewTimeline }: Props) {
  const [activeTab, setActiveTab] = useState<TabType>('report');
  const [expandedRow, setExpandedRow] = useState<number | null>(null);
  const [showChat, setShowChat] = useState(false);

  const rxguardPatient = useMemo(() => mapPrescriptionToRxGuard(prescription, patientProfile), [prescription, patientProfile]);
  const prescriptionSummary = useMemo(() => `${prescription.Medications?.length || 0} medications · ${prescription.PatientName || 'Patient'}`, [prescription]);

  const hasCritical = clinicalData?.interactions?.has_critical;
  const medsCount = prescription.Medications.length;
  const correctedCount = prescription.Medications.filter(m => m.correction_trace?.correction_applied).length;

  /* ── CLINICAL REPORT ── */
  const renderReport = () => (
    <div className="space-y-5">
      {/* Summary card */}
      <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm">
        <div className="flex items-start justify-between mb-5">
          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-1">Clinical Analysis Summary</h2>
            <p className="text-sm text-gray-500">Generated by the MedLens clinical intelligence engine.</p>
          </div>
          <span className={`flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-full border ${hasCritical ? 'bg-red-50 text-red-700 border-red-200' : 'bg-emerald-50 text-emerald-700 border-emerald-200'}`}>
            {hasCritical ? <AlertTriangle className="w-3.5 h-3.5" /> : <CheckCircle2 className="w-3.5 h-3.5" />}
            {hasCritical ? 'Action required' : 'No critical findings'}
          </span>
        </div>

        {/* Meta row */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6 pb-6 border-b border-gray-100">
          {[
            { label: 'Patient', value: prescription.PatientName || '—' },
            { label: 'Prescriber', value: prescription.PrescriberName || '—' },
            { label: 'Date', value: prescription.Date || '—' },
            { label: 'Compounds', value: `${medsCount} identified` },
          ].map((item, i) => (
            <div key={i}>
              <p className="text-[11px] text-gray-400 font-medium uppercase tracking-wider mb-1">{item.label}</p>
              <p className="text-sm font-semibold text-gray-900">{item.value}</p>
            </div>
          ))}
        </div>

        {/* Narrative */}
        <div className="prose prose-sm prose-gray max-w-none text-gray-600 leading-relaxed">
          <p>
            The clinical engine has successfully parsed and validated the prescription for <strong className="text-gray-900">{prescription.PatientName || 'the patient'}</strong>. 
            A total of <strong className="text-gray-900">{medsCount} pharmacological compound{medsCount !== 1 ? 's' : ''}</strong> were extracted and cross-referenced against the regional drug index.
            {correctedCount > 0 && ` ${correctedCount} OCR-extracted token${correctedCount > 1 ? 's were' : ' was'} automatically resolved using fuzzy matching.`}
          </p>
          <p className="mt-3">
            {hasCritical
              ? 'Critical pharmacological conflicts have been detected. Immediate review of the Drug Interactions section is recommended before dispensing. Professional clinical override may be required.'
              : 'No critical drug interactions were identified. All extracted dosages fall within standard therapeutic ranges based on available patient parameters. The prescription appears safe for dispensing pending pharmacist review.'}
          </p>
          {clinicalData?.insurance?.financial_summary?.savings_via_generics_inr > 0 && (
            <p className="mt-3">
              Generic substitution opportunities are available, with potential patient savings of <strong className="text-gray-900">₹{clinicalData.insurance.financial_summary.savings_via_generics_inr}</strong> relative to branded formulations.
            </p>
          )}
        </div>
      </div>

      {/* Quick stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {[
          { label: 'Interactions', value: clinicalData?.interactions?.conflicts?.length || 0, color: hasCritical ? 'text-red-600' : 'text-emerald-600', bg: hasCritical ? 'bg-red-50 border-red-200' : 'bg-emerald-50 border-emerald-200' },
          { label: 'Dosage flags', value: clinicalData?.dosageSanity?.results?.filter((r: any) => r.plausibility !== 'plausible')?.length || 0, color: 'text-amber-600', bg: 'bg-amber-50 border-amber-200' },
          { label: 'Food warnings', value: clinicalData?.foodWarnings?.warnings?.length || 0, color: 'text-orange-600', bg: 'bg-orange-50 border-orange-200' },
          { label: 'Formulary coverage', value: `${clinicalData?.insurance?.financial_summary ? Math.round((clinicalData.insurance.financial_summary.insurer_covered_amount_inr / (clinicalData.insurance.financial_summary.total_prescription_cost_inr || 1)) * 100) : 0}%`, color: 'text-blue-600', bg: 'bg-blue-50 border-blue-200' },
        ].map((s, i) => (
          <div key={i} className={`${s.bg} border rounded-xl p-4`}>
            <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
            <p className="text-xs text-gray-500 font-medium mt-0.5">{s.label}</p>
          </div>
        ))}
      </div>

      {/* CTA to consultant */}
      <div className="bg-gray-900 rounded-2xl p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h3 className="text-white font-semibold mb-1">Ask the Clinical Consultant</h3>
          <p className="text-gray-400 text-sm">Discuss this report, explore drug interactions, or clarify dosage protocols with the advisory intelligence layer.</p>
        </div>
        <button
          onClick={() => setShowChat(true)}
          className="shrink-0 flex items-center gap-2 bg-white text-gray-900 px-5 py-2.5 rounded-xl text-sm font-semibold hover:bg-gray-100 transition-colors"
        >
          <MessageSquare className="w-4 h-4" /> Open Consultant <ChevronRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );

  /* ── MEDICATIONS OVERVIEW ── */
  const renderOverview = () => (
    <div className="space-y-5">
      <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
          <h3 className="text-sm font-semibold text-gray-900">Extracted medications ({medsCount})</h3>
          <button onClick={onViewTimeline} className="flex items-center gap-1.5 text-xs font-semibold text-gray-600 hover:text-gray-900 bg-gray-50 border border-gray-200 px-3 py-1.5 rounded-lg hover:border-gray-300 transition-all">
            <CalendarClock className="w-3.5 h-3.5" /> View timeline
          </button>
        </div>
        {correctedCount > 0 && (
          <div className="px-5 py-3 bg-amber-50 border-b border-amber-100 flex items-center gap-2 text-xs text-amber-700 font-medium">
            <AlertCircle className="w-4 h-4" /> {correctedCount} drug name{correctedCount > 1 ? 's' : ''} auto-corrected via OCR fuzzy matching.
          </div>
        )}
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                {['Drug', 'OCR Trace', 'Dose', 'Frequency', 'Duration', 'Instructions', 'Confidence'].map(h => (
                  <th key={h} className="px-5 py-3.5 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {prescription.Medications.map((m, i) => (
                <React.Fragment key={i}>
                  <tr className="hover:bg-gray-50 transition-colors">
                    <td className="px-5 py-3.5 font-semibold text-gray-900 text-sm whitespace-nowrap">{m.DrugName}</td>
                    <td className="px-5 py-3.5">
                      {m.correction_trace?.correction_applied ? (
                        <button onClick={() => setExpandedRow(expandedRow === i ? null : i)} className="flex items-center gap-1.5 text-xs font-medium text-amber-700 bg-amber-50 border border-amber-200 px-2.5 py-1 rounded-full hover:bg-amber-100 transition-colors whitespace-nowrap">
                          <span className="line-through opacity-60">{m.correction_trace.raw_ocr_text}</span>→{m.correction_trace.matched_drug}
                        </button>
                      ) : (
                        <span className="flex items-center gap-1 text-xs text-emerald-700 font-medium"><CheckCircle2 className="w-3 h-3" />Exact</span>
                      )}
                    </td>
                    <td className="px-5 py-3.5 text-sm text-gray-600 whitespace-nowrap">{m.DoseValue} {m.DoseUnit !== 'MISSING' ? m.DoseUnit : ''}</td>
                    <td className="px-5 py-3.5 text-sm text-gray-600">{m.Frequency}</td>
                    <td className="px-5 py-3.5 text-sm text-gray-600">{m.Duration !== 'MISSING' ? m.Duration : '—'}</td>
                    <td className="px-5 py-3.5 text-sm text-gray-600">{m.AdminInstructions !== 'MISSING' ? m.AdminInstructions : '—'}</td>
                    <td className="px-5 py-3.5"><Badge level={m.ConfidenceLevel} /></td>
                  </tr>
                  {expandedRow === i && m.correction_trace?.correction_applied && (
                    <tr><td colSpan={7} className="bg-gray-50 px-5 py-4 border-t border-gray-100">
                      <div className="text-xs font-mono text-gray-500 space-y-1">
                        <p><span className="text-gray-400 w-32 inline-block">Raw OCR:</span> <span className="text-red-600">"{m.correction_trace.raw_ocr_text}"</span></p>
                        <p><span className="text-gray-400 w-32 inline-block">Resolved:</span> <span className="text-emerald-600 font-semibold">{m.correction_trace.matched_drug}</span></p>
                        <p><span className="text-gray-400 w-32 inline-block">Method:</span> {m.correction_trace.method}</p>
                        <p><span className="text-gray-400 w-32 inline-block">Similarity:</span> {m.correction_trace.rapidfuzz_score}/100 · {m.correction_trace.levenshtein_distance} edit(s)</p>
                      </div>
                    </td></tr>
                  )}
                </React.Fragment>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );

  /* ── INTERACTIONS ── */
  const renderInteractions = () => {
    const interactions = clinicalData?.interactions;
    if (!interactions?.conflicts?.length) return (
      <div className="bg-white border border-gray-200 rounded-2xl p-16 text-center shadow-sm">
        <CheckCircle2 className="w-12 h-12 text-emerald-500 mx-auto mb-4" />
        <h3 className="text-base font-semibold text-gray-900 mb-1">No interactions detected</h3>
        <p className="text-sm text-gray-500">All prescribed compounds appear pharmacologically compatible.</p>
      </div>
    );
    return (
      <div className="space-y-4">
        {hasCritical && (
          <div className="flex items-start gap-3 p-4 bg-red-50 border border-red-200 rounded-xl">
            <AlertTriangle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
            <div><p className="text-sm font-semibold text-red-800">Critical conflict detected</p><p className="text-xs text-red-600 mt-0.5">Review all flagged combinations before dispensing.</p></div>
          </div>
        )}
        {interactions.conflicts.map((c: any, i: number) => (
          <div key={i} className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
            <div className="flex items-center justify-between p-5 border-b border-gray-100">
              <div className="flex items-center gap-3">
                <span className="font-semibold text-gray-900 text-sm">{c.drug_a}</span>
                <span className="text-gray-300 text-xs font-bold">×</span>
                <span className="font-semibold text-gray-900 text-sm">{c.drug_b}</span>
              </div>
              <Badge level={c.severity} />
            </div>
            <div className="p-5 grid sm:grid-cols-2 gap-5">
              <div><p className="text-[11px] font-semibold text-gray-400 uppercase tracking-wider mb-1.5">Mechanism</p><p className="text-sm text-gray-700 leading-relaxed">{c.mechanism}</p></div>
              <div><p className="text-[11px] font-semibold text-gray-400 uppercase tracking-wider mb-1.5">Consequence</p><p className="text-sm text-gray-700 leading-relaxed">{c.consequence}</p></div>
            </div>
            <div className="px-5 py-4 bg-gray-50 border-t border-gray-100 flex items-start justify-between gap-3">
              <p className="text-xs text-gray-600"><span className="font-semibold text-gray-800">Recommended action:</span> {c.pharmacist_action}</p>
              {c.substitution_suggestion && <p className="text-xs text-gray-500 shrink-0">Alt: {c.substitution_suggestion}</p>}
            </div>
          </div>
        ))}
      </div>
    );
  };

  /* ── DOSAGE ── */
  const renderDosage = () => {
    const sanity = clinicalData?.dosageSanity?.results;
    if (!sanity) return <div className="p-8 text-center text-sm text-gray-500">Dosage data unavailable.</div>;
    return (
      <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>{['Drug', 'Dose', 'Assessment', 'Detail'].map(h => <th key={h} className="px-5 py-3.5 text-xs font-semibold text-gray-500 uppercase tracking-wider">{h}</th>)}</tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {prescription.Medications.map((m, i) => {
                const res = sanity.find((r: any) => r.drug_name === m.DrugName);
                const status = res?.plausibility || 'unverified';
                const badge = status === 'plausible' || status === 'safe' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : status === 'dangerous' ? 'bg-red-50 text-red-700 border-red-200' : status === 'implausible' ? 'bg-amber-50 text-amber-700 border-amber-200' : 'bg-gray-100 text-gray-500 border-gray-200';
                return (
                  <tr key={i} className="hover:bg-gray-50 transition-colors">
                    <td className="px-5 py-4 font-semibold text-gray-900 text-sm">{m.DrugName}</td>
                    <td className="px-5 py-4 text-sm text-gray-600">{m.DoseValue} {m.DoseUnit}</td>
                    <td className="px-5 py-4"><span className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded border ${badge}`}>{status}</span></td>
                    <td className="px-5 py-4 text-sm text-gray-500">{res?.reason || '—'}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    );
  };

  /* ── INSURANCE ── */
  const renderInsurance = () => {
    const ins = clinicalData?.insurance;
    if (!ins) return null;
    const fs = ins.financial_summary;
    return (
      <div className="space-y-5">
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          {[
            { label: 'Total (Brand)', value: `₹${fs.total_prescription_cost_inr}`, color: 'text-gray-900' },
            { label: 'Insurer covers', value: `₹${fs.insurer_covered_amount_inr}`, color: 'text-emerald-600' },
            { label: 'Generic savings', value: `₹${fs.savings_via_generics_inr}`, color: 'text-blue-600' },
            { label: 'You pay', value: `₹${fs.final_out_of_pocket_inr}`, color: 'text-violet-700', highlight: true },
          ].map((s, i) => (
            <div key={i} className={`bg-white border rounded-xl p-4 shadow-sm ${s.highlight ? 'border-violet-200' : 'border-gray-200'}`}>
              <p className="text-[11px] text-gray-400 font-medium uppercase tracking-wider mb-1">{s.label}</p>
              <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
            </div>
          ))}
        </div>
        <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead className="bg-gray-50 border-b border-gray-100">
                <tr>{['Drug', 'Coverage', 'Generic', 'Brand price', 'Generic price'].map(h => <th key={h} className="px-5 py-3.5 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">{h}</th>)}</tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {ins.drugs.map((d: any, i: number) => {
                  const sc = d.coverage_status === 'covered' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : d.coverage_status === 'not_covered' ? 'bg-red-50 text-red-700 border-red-200' : 'bg-amber-50 text-amber-700 border-amber-200';
                  return (
                    <tr key={i} className="hover:bg-gray-50 transition-colors">
                      <td className="px-5 py-4 font-semibold text-gray-900 text-sm">{d.drug_name}</td>
                      <td className="px-5 py-4"><span className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded border ${sc}`}>{d.coverage_status.replace(/_/g, ' ')}</span></td>
                      <td className="px-5 py-4 text-sm text-gray-600">{d.generic_alternative || '—'}</td>
                      <td className="px-5 py-4 text-sm text-gray-500">₹{d.brand_price_inr}</td>
                      <td className="px-5 py-4 text-sm font-semibold text-emerald-700">₹{d.generic_price_inr}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    );
  };

  /* ── FOOD ── */
  const renderFood = () => {
    const warnings = clinicalData?.foodWarnings?.warnings;
    if (!warnings?.length) return (
      <div className="bg-white border border-gray-200 rounded-2xl p-16 text-center shadow-sm">
        <Apple className="w-12 h-12 text-emerald-500 mx-auto mb-4" />
        <h3 className="text-base font-semibold text-gray-900 mb-1">No dietary restrictions</h3>
        <p className="text-sm text-gray-500">No known food-drug interactions for the prescribed compounds.</p>
      </div>
    );
    return (
      <div className="grid sm:grid-cols-2 gap-4">
        {warnings.map((w: any, i: number) => (
          <div key={i} className="bg-white border border-gray-200 rounded-2xl shadow-sm p-5">
            <div className="flex items-center justify-between mb-3">
              <p className="text-sm font-semibold text-gray-900">{w.drug_name} <span className="text-gray-400 font-normal">with</span> {w.food_item}</p>
              <Badge level={w.severity} />
            </div>
            <p className="text-xs text-gray-500 mb-3 font-medium">{w.interaction_type}</p>
            <p className="text-sm text-gray-700 bg-gray-50 rounded-lg p-3 leading-relaxed">{w.recommendation}</p>
          </div>
        ))}
      </div>
    );
  };

  /* ── VALIDITY ── */
  const renderValidity = () => {
    const v = clinicalData?.validity;
    if (!v) return null;
    return (
      <div className="max-w-2xl space-y-5">
        <div className={`border rounded-2xl p-6 text-center ${v.legally_complete ? 'bg-emerald-50 border-emerald-200' : 'bg-amber-50 border-amber-200'}`}>
          <p className={`text-4xl font-bold mb-1 ${v.legally_complete ? 'text-emerald-700' : 'text-amber-700'}`}>{v.score}</p>
          <p className={`text-sm font-semibold ${v.legally_complete ? 'text-emerald-700' : 'text-amber-700'}`}>
            {v.legally_complete ? 'Prescription meets dispensing standards' : 'Compliance issues detected'}
          </p>
        </div>
        <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
          {v.criteria.map((c: any, i: number) => (
            <div key={i} className={`flex items-start gap-4 p-4 ${i > 0 ? 'border-t border-gray-100' : ''}`}>
              {c.passed ? <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0 mt-0.5" /> : <AlertTriangle className="w-5 h-5 text-red-500 shrink-0 mt-0.5" />}
              <div><p className={`text-sm font-semibold ${c.passed ? 'text-gray-900' : 'text-red-700'}`}>{c.name}</p><p className="text-xs text-gray-500 mt-0.5">{c.detail}</p></div>
            </div>
          ))}
        </div>
      </div>
    );
  };

  const renderMap: Record<TabType, () => React.ReactNode> = {
    report: renderReport, overview: renderOverview, interactions: renderInteractions,
    dosage: renderDosage, insurance: renderInsurance, food: renderFood, validity: renderValidity,
  };

  return (
    <div className="space-y-5 animate-fadeSlideUp">
      {/* Tab bar */}
      <div className="flex items-center gap-1 bg-gray-100 p-1 rounded-xl overflow-x-auto">
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold whitespace-nowrap transition-all ${
              activeTab === tab.id ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'
            }`}
          >
            <tab.icon className="w-3.5 h-3.5" />{tab.label}
          </button>
        ))}
        <div className="ml-auto shrink-0">
          <button
            onClick={() => setShowChat(true)}
            className="flex items-center gap-1.5 px-3 py-2 bg-gray-900 text-white rounded-lg text-xs font-semibold hover:bg-gray-800 transition-colors whitespace-nowrap"
          >
            <MessageSquare className="w-3.5 h-3.5" /> Clinical Consultant
          </button>
        </div>
      </div>

      {/* Content */}
      <div>{renderMap[activeTab]()}</div>

      {/* Chat drawer */}
      {showChat && (
        <>
          <div className="fixed inset-0 bg-black/20 backdrop-blur-[2px] z-40" onClick={() => setShowChat(false)} />
          <RxGuardChat rxguardPatient={rxguardPatient} prescriptionSummary={prescriptionSummary} onClose={() => setShowChat(false)} />
        </>
      )}
    </div>
  );
}
